import "npm:svelte2tsx@0.6.23/svelte-jsx.d.ts";
import "npm:svelte2tsx@0.6.23/svelte-shims.d.ts";
;function render() {

   let name: string = "world"/*Ωignore_startΩ*/;name = __sveltets_2_any(name);/*Ωignore_endΩ*/;

  // <!-- <script>
  //   export let name = "world"; -->
;
async () => {

 { svelteHTML.createElement("h1", {}); name;  }
};
return { props: {name: name}, slots: {}, events: {} }}

export class TsxComponent extends __sveltets_2_createSvelte2TsxComponent(__sveltets_2_partial(['name'], __sveltets_2_with_any_event(render()))) {
}
/* generated by Svelte v4.2.1 */
import { create_ssr_component, escape } from "npm:svelte@4.2.1/internal";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { name = "world" } = $$props;
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	return `<h1>Hello ${escape(name)}!</h1>`;
});

export default Component;