/* generated by Svelte v3.58.0 */
import {
	create_ssr_component,
	each,
	escape,
	validate_component
} from "svelte/internal";

import BookPage from "./book_page.svelte";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data = [] } = $$props;
	let x = 0;
	x++;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `${escape(x)}

${each(data, book => {
		return `${validate_component(BookPage, "BookPage").$$render(
			$$result,
			{
				content: book.content,
				caption: book.caption
			},
			{},
			{}
		)}`;
	})}`;
});

export default Component;